export type RiskStatus = 'draft' | 'voting_in_progress' | 'assessed' | 'in_treatment' | 'monitoring'
export type ReviewPeriod = '1m' | '3m' | '6m' | '1y'

export interface Risk {
  id: string
  title: string
  category: string
  status: RiskStatus
  likelihood: number | null
  impact: number | null
  score: number | null
  description: string
  causes?: string
  consequences?: string
  owner?: string
  createdAt: string
  reviewPeriod?: ReviewPeriod
  nextReview?: string
  dispersionFlag?: boolean
}

export const risks: Risk[] = [
  {
    id: 'r1',
    title: 'Витік персональних даних клієнтів',
    category: 'Технологічний / Кібер',
    status: 'monitoring',
    likelihood: 4,
    impact: 5,
    score: 18,
    description: 'Можливий витік даних через вразливість в API платіжного шлюзу. Зачеплені дані понад 50 000 клієнтів.',
    causes: 'Застаріла версія бібліотеки авторизації. Відсутність ротації ключів API.',
    consequences: 'Штраф регулятора до 2% обороту. Репутаційна шкода. Відтік клієнтів.',
    owner: 'u1',
    createdAt: '2024-10-15',
    reviewPeriod: '6m',
    nextReview: '2025-04-15',
    dispersionFlag: true,
  },
  {
    id: 'r2',
    title: 'Зміна регуляторних вимог НБУ',
    category: 'Комплаєнс / Регуляторний',
    status: 'draft',
    likelihood: null,
    impact: null,
    score: null,
    description: 'НБУ планує посилити вимоги до достатності капіталу для небанківських фінансових організацій.',
    causes: 'Глобальне посилення регулювання фінансового сектору після кризи 2023 року.',
    consequences: 'Необхідність доформування резервів на суму до 500 млн грн. Обмеження кредитного портфеля.',
    owner: 'u1',
    createdAt: '2024-11-02',
    reviewPeriod: '3m',
  },
  {
    id: 'r3',
    title: 'Звільнення ключових IT-спеціалістів',
    category: 'Операційний / Персонал',
    status: 'in_treatment',
    likelihood: 4,
    impact: 3,
    score: 12,
    description: 'Високий попит на ринку праці створює ризик відходу ключових розробників платіжної системи.',
    owner: 'u1',
    createdAt: '2024-10-20',
    reviewPeriod: '3m',
    nextReview: '2025-01-20',
  },
  {
    id: 'r4',
    title: 'Збій платіжної інфраструктури',
    category: 'Операційний / Технологічний',
    status: 'assessed',
    likelihood: 2,
    impact: 5,
    score: 10,
    description: 'Можливий збій основного платіжного процесора через технічні несправності або DDoS-атаку.',
    owner: 'u1',
    createdAt: '2024-10-28',
    reviewPeriod: '3m',
    nextReview: '2025-01-28',
  },
  {
    id: 'r5',
    title: 'Шахрайство з боку третіх осіб',
    category: 'Фінансовий',
    status: 'monitoring',
    likelihood: 3,
    impact: 4,
    score: 12,
    description: 'Участілі випадки шахрайства з використанням скомпрометованих облікових даних клієнтів.',
    owner: 'u1',
    createdAt: '2024-09-12',
    reviewPeriod: '6m',
    nextReview: '2025-03-12',
  },
  {
    id: 'r6',
    title: 'Недостатній рівень кіберграмотності персоналу',
    category: 'Операційний / Персонал',
    status: 'draft',
    likelihood: null,
    impact: null,
    score: null,
    description: 'Співробітники схильні відкривати фішингові листи, що створює загрозу компрометації внутрішніх систем.',
    owner: 'u1',
    createdAt: '2024-11-05',
    reviewPeriod: '6m',
  },
  {
    id: 'r7',
    title: 'Концентрація ключових клієнтів',
    category: 'Стратегічний',
    status: 'assessed',
    likelihood: 2,
    impact: 3,
    score: 6,
    description: 'Три найбільших клієнти формують 60% виручки, що створює високу залежність.',
    owner: 'u1',
    createdAt: '2024-10-01',
    reviewPeriod: '6m',
    nextReview: '2025-04-01',
  },
  {
    id: 'r8',
    title: 'Відмова хмарного провайдера',
    category: 'Операційний / Технологічний',
    status: 'monitoring',
    likelihood: 1,
    impact: 5,
    score: 5,
    description: 'Повна або часткова відмова хмарної інфраструктури AWS, яка обслуговує ядро платформи.',
    causes: 'Технічні збої на стороні провайдера, природні катастрофи, помилки конфігурації.',
    consequences: 'Недоступність сервісу до 24 годин. Фінансові втрати від простою.',
    owner: 'u1',
    createdAt: '2024-09-05',
    reviewPeriod: '6m',
    nextReview: '2025-03-05',
  },
  {
    id: 'r9',
    title: 'Валютний ризик при міжнародних розрахунках',
    category: 'Фінансовий',
    status: 'assessed',
    likelihood: 3,
    impact: 3,
    score: 9,
    description: 'Коливання курсу гривні до євро та долара негативно впливають на маржу по міжнародних транзакціях.',
    causes: 'Нестабільність валютного ринку, геополітична напруженість.',
    consequences: 'Зниження маржинальності на 1–2%. Непередбачувані збитки по хеджуванню.',
    owner: 'u1',
    createdAt: '2024-10-10',
    reviewPeriod: '3m',
    nextReview: '2025-01-10',
  },
  {
    id: 'r10',
    title: 'Атака на ланцюг постачання ПЗ',
    category: 'Технологічний / Кібер',
    status: 'in_treatment',
    likelihood: 3,
    impact: 5,
    score: 15,
    description: 'Компрометація сторонньої бібліотеки або npm-пакету може призвести до виконання шкідливого коду.',
    causes: 'Вразливість у відкритих залежностях. Відсутність перевірки цілісності пакетів.',
    consequences: 'Компрометація виробничого середовища. Крадіжка ключів та токенів.',
    owner: 'u1',
    createdAt: '2024-11-10',
    reviewPeriod: '3m',
    nextReview: '2025-02-10',
  },
  {
    id: 'r11',
    title: 'Несанкціонований доступ до бази даних',
    category: 'Технологічний / Кібер',
    status: 'monitoring',
    likelihood: 2,
    impact: 5,
    score: 10,
    description: 'Зловмисники можуть отримати прямий доступ до PostgreSQL-кластера через вразливості в мережевому периметрі.',
    causes: 'Неправильна конфігурація Security Groups. Використання слабких паролів сервісних акаунтів.',
    consequences: 'Витік усіх клієнтських даних. Порушення вимог GDPR та законодавства про захист даних.',
    owner: 'u1',
    createdAt: '2024-10-22',
    reviewPeriod: '6m',
    nextReview: '2025-04-22',
  },
  {
    id: 'r12',
    title: 'Затримка виходу нового продукту',
    category: 'Стратегічний',
    status: 'assessed',
    likelihood: 4,
    impact: 2,
    score: 8,
    description: 'Ризик зриву строків запуску нового продукту через технічний борг та нестачу ресурсів.',
    causes: 'Неефективне планування спринтів. Технічний борг накопичений за 2 роки.',
    consequences: 'Втрата ринкового вікна. Упущений дохід від раннього запуску.',
    owner: 'u1',
    createdAt: '2024-11-15',
    reviewPeriod: '1m',
    nextReview: '2025-01-15',
  },
  {
    id: 'r13',
    title: 'Масовий відтік клієнтів через UX',
    category: 'Стратегічний',
    status: 'draft',
    likelihood: null,
    impact: null,
    score: null,
    description: 'Незручний інтерфейс мобільного застосунку провокує відтік користувачів до конкурентів.',
    causes: 'Відсутність регулярного UX-аудиту. Ігнорування зворотного зв\'язку від користувачів.',
    consequences: 'Зниження MAU на 15–20%. Зниження виручки від комісій.',
    owner: 'u1',
    createdAt: '2024-11-20',
    reviewPeriod: '3m',
  },
  {
    id: 'r14',
    title: 'Порушення вимог PCI DSS',
    category: 'Комплаєнс / Регуляторний',
    status: 'in_treatment',
    likelihood: 5,
    impact: 5,
    score: 25,
    description: 'Невідповідність стандарту PCI DSS рівня 1 через відсутність шифрування в окремих мікросервісах.',
    causes: 'Відсутність систематичного аудиту відповідності. Швидке масштабування без дотримання стандартів безпеки.',
    consequences: 'Штраф до $500 000. Призупинення платіжної ліцензії. Обов\'язковий зовнішній аудит.',
    owner: 'u1',
    createdAt: '2024-10-05',
    reviewPeriod: '1m',
    nextReview: '2025-01-05',
  },
]
